version: 0.2

env:
  variables:
    S3_BUCKET: "apex-offensive-landing-site"
    CLOUDFRONT_ID: "E37DPWW9S4WXLN"


phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo "Syncing site folder to S3..."
      - aws s3 sync ./site/ s3://$S3_BUCKET/ --delete

  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"